/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal.vistas;

import idiomas.modelos.GestorIdiomas;
import interfaces.IControladorPrincipal;
import interfaces.IGestorIdiomas;
import interfaces.IGestorLugares;
import interfaces.IGestorPalabrasClaves;
import interfaces.IGestorTipos;
import lugares.modelos.GestorLugares;
import palabrasclaves.modelos.GestorPalabrasClaves;
import principal.controladores.ControladorPrincipal;
import tipos.modelos.GestorTipos;

/**
 *
 * @author Windows 10
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private IControladorPrincipal controlador;
    /**
     * Creates new form VentanaPrincipal
     * @param ControladorPrincipal
     */
    

    public VentanaPrincipal(IControladorPrincipal controlador) {
        this.controlador = controlador;
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnAutores = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Repositorios");

        jButton1.setText("Palabras Claves");

        jButton2.setText("Lugares");

        jButton3.setText("Idiomas");

        jButton4.setText("Tipos");

        jButton5.setText("Grupos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGruposClic(evt);
            }
        });

        btnAutores.setText("Autores");
        btnAutores.setToolTipText("Sección Autores");
        btnAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoresClic(evt);
            }
        });

        jButton7.setText("Publicaciones");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublicacionesClic(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.setToolTipText("Cerrar el Programa");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirClic(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirClic(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirClic
        this.controlador.btnSalirClic(evt);
    }//GEN-LAST:event_btnSalirClic

    private void btnAutoresClic(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoresClic
        this.controlador.btnAutoresClic(evt);
    }//GEN-LAST:event_btnAutoresClic

    private void btnGruposClic(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGruposClic
        this.controlador.btnGruposClic(evt);
    }//GEN-LAST:event_btnGruposClic

    private void btnPublicacionesClic(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublicacionesClic
        this.controlador.btnPublicacionesClic(evt);
    }//GEN-LAST:event_btnPublicacionesClic

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        IGestorLugares lugar = GestorLugares.crear();
        IGestorIdiomas idioma = GestorIdiomas.crear();
        IGestorTipos tipo = GestorTipos.crear();
        IGestorPalabrasClaves palabraClave = GestorPalabrasClaves.crear();
        
//        System.out.println("------------------INGRESO DE IDIOMAS------------------");
        idioma.nuevoIdioma("Inglés");
        idioma.nuevoIdioma("Inglés");//REPETIDO
        idioma.nuevoIdioma("Español");
        idioma.nuevoIdioma("Japones");
        idioma.nuevoIdioma("Aleman");
        idioma.nuevoIdioma("");//VACIO
        idioma.nuevoIdioma(null);//NULO
//        System.out.println("------------------------------------------------------");
        
//        System.out.println("------------------INGRESO DE TIPOS------------------");
        tipo.nuevoTipo("tipo2");
        tipo.nuevoTipo("tipo1");
        tipo.nuevoTipo("tipo3");
        tipo.nuevoTipo("tipo4");
        tipo.nuevoTipo("tipo1");//REPETIDO
        tipo.nuevoTipo("");//VACIO
        tipo.nuevoTipo(null);//NULO
//        System.out.println("------------------------------------------------------");
        
//        System.out.println("------------------INGRESO DE LUGARES------------------");
        lugar.nuevoLugar("lugar1");
        lugar.nuevoLugar("lugar1");//REPETIDO
        lugar.nuevoLugar("lugar2");
        lugar.nuevoLugar("lugar3");
        lugar.nuevoLugar("lugar4");
        lugar.nuevoLugar("");//VACIO
        lugar.nuevoLugar(null);//NULO
//        System.out.println("------------------------------------------------------");
        
//        System.out.println("------------------INGRESO DE PALABRAS CLAVE------------------");
        palabraClave.nuevaPalabraClave("pc1");
        palabraClave.nuevaPalabraClave("pc1");//REPETIDO
        palabraClave.nuevaPalabraClave("pc2");
        palabraClave.nuevaPalabraClave("pc3");
        palabraClave.nuevaPalabraClave("pc4");
        palabraClave.nuevaPalabraClave("");//VACIO
        palabraClave.nuevaPalabraClave(null);//NULO
//        System.out.println("------------------------------------------------------");
        
        IControladorPrincipal controlador = new ControladorPrincipal();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutores;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    // End of variables declaration//GEN-END:variables
}
